CREATE TABLE Tenants (
    Id UNIQUEIDENTIFIER NOT NULL PRIMARY KEY,
    Name NVARCHAR(200) NOT NULL,
    CreatedAtUtc DATETIME2 NOT NULL DEFAULT SYSUTCDATETIME()
);

CREATE TABLE Messages (
    Id UNIQUEIDENTIFIER NOT NULL PRIMARY KEY,
    TenantId UNIQUEIDENTIFIER NOT NULL,
    Channel NVARCHAR(30) NOT NULL,
    Recipient NVARCHAR(320) NOT NULL,
    Subject NVARCHAR(500) NULL,
    Body NVARCHAR(MAX) NOT NULL,
    Status NVARCHAR(30) NOT NULL,
    ProviderMessageId NVARCHAR(200) NULL,
    CreatedAtUtc DATETIME2 NOT NULL DEFAULT SYSUTCDATETIME(),
    UpdatedAtUtc DATETIME2 NULL,
    CONSTRAINT FK_Messages_Tenants FOREIGN KEY (TenantId) REFERENCES Tenants(Id)
);

CREATE INDEX IX_Messages_TenantId_CreatedAt
ON Messages(TenantId, CreatedAtUtc DESC);

CREATE TABLE MessageEvents (
    Id BIGINT IDENTITY PRIMARY KEY,
    MessageId UNIQUEIDENTIFIER NOT NULL,
    EventType NVARCHAR(50) NOT NULL,
    ProviderPayload NVARCHAR(MAX) NULL,
    CreatedAtUtc DATETIME2 NOT NULL DEFAULT SYSUTCDATETIME(),
    CONSTRAINT FK_MessageEvents_Messages FOREIGN KEY (MessageId) REFERENCES Messages(Id)
);
